### PR TITLE
workflow: Create and upload debug bundle to nRF Cloud

### PR DESCRIPTION
**Pull request by gregersrygg**
To allow FOTA update to the debug version.

### CODE REVIEW

**Comment by gregersrygg** [comment]
@coderbyheart I'm not sure what the <configuration> part of the filename was used for before, but it seems like it's not being used anymore after the renaming of assets @maxd-nordic did a while ago. So I took the liberty to re-use it for the `+debug` build. Please let me know if that's wrong use of the `configuration` capturing group.

**Comment by coderbyheart** [comment]
Yeah, that is a convention we had in asset_tracker_v2 and ThingyWorld firmwares where we had low-power and debug builds for the same device.

Change looks good, I simple added a test for the RegEx.

**Comment by coderbyheart** [comment]
> To allow FOTA update to the debug version.

It's not clear how the change to the filename allows this, and why it was not possible before.

**Comment by gregersrygg** [comment]
> > To allow FOTA update to the debug version.
> 
> It's not clear how the change to the filename allows this, and why it was not possible before.

That description was for the PR, which updates the regex to not filter out the debug binary. Then both the original binary and the debug binary will get a bundle and registered in nrf cloud.

The change to the filename was done separately. Max had a cleanup of the filenames, and when I added the debug variant, it seemed natural to use the metadata portion of semver instead of having it separate from the version string.

**Comment by coderbyheart** [comment]
Ah, I see.

**Pull request merged**
