### PR TITLE
wip: projectwide: update sdk-nrf

### PR DESCRIPTION
**Pull request by maxd-nordic**
Update NCS to 2.8 RC1

### CODE REVIEW

**Comment by maxd-nordic** [comment]
RC1 is not there yet, but we will be very soon, we can already prepare here.

**Comment by maxd-nordic** [comment]
we have to wait for these PRs:
https://github.com/nrfconnect/sdk-mcuboot/pull/356
https://github.com/nrfconnect/sdk-nrf/pull/18125
https://github.com/nrfconnect/sdk-nrf/pull/18121

After, we'll remove the temp commits

**Comment by simensrostad** [comment]
We will likely need to make changes to support the new link controller structure:

https://github.com/nrfconnect/sdk-nrf/pull/17266

**Comment by trantanen** [comment]
> We will likely need to make changes to support the new link controller structure:
> 
> [nrfconnect/sdk-nrf#17266](https://github.com/nrfconnect/sdk-nrf/pull/17266)

You need to set `CONFIG_LTE_LC_PSM_MODULE=y` and `CONFIG_LTE_LC_EDRX_MODULE=y` in your prj.conf. This can be now done as lte_lc refactoring PR was merged yesterday evening.

**Comment by simensrostad** [comment]
> > We will likely need to make changes to support the new link controller structure:
> > [nrfconnect/sdk-nrf#17266](https://github.com/nrfconnect/sdk-nrf/pull/17266)
> 
> You need to set `CONFIG_LTE_LC_PSM_MODULE=y` and `CONFIG_LTE_LC_EDRX_MODULE=y` in your prj.conf. This can be now done as lte_lc refactoring PR was merged yesterday evening.

And CONFIG_LTE_LC_CONN_EVAL_MODULE 🚀

**Pull request merged**
