### PR TITLE
Add environmental module

### PR DESCRIPTION
**Pull request by maxd-nordic**

### CODE REVIEW

**Review by balaji-nordic — COMMENTED** [review]
Was it necessary to check in the generated code to git? Was thinking we can keep in the build folder and not commit them in.

**Comment by maxd-nordic** [comment]
> Was it necessary to check in the generated code to git? I prefer to keep them in the build folder and not commit them in.

Necessary is a strong word, but it is in line with how it's done in NCS. We can refactor this if needed.

**Comment by simensrostad** [comment]
> > Was it necessary to check in the generated code to git? I prefer to keep them in the build folder and not commit them in.
> 
> Necessary is a strong word, but it is in line with how it's done in NCS. We can refactor this if needed.

I think we should avoid checking in generated code, its not necessary. Its up to use to decide. For instance for wifi prov stuff I didn't do it.

I think you also can do some tricks that prevents the code from being generated in source, but rather in build. That is supported when using protobuf.

**Comment by balaji-nordic** [comment]
> I think you also can do some tricks that prevents the code from being generated in source, but rather in build. That is supported when using protobuf.

This is doable using cmake. I can help out if needed.

**Comment by maxd-nordic** [comment]
> > I think you also can do some tricks that prevents the code from being generated in source, but rather in build. That is supported when using protobuf.
> 
> This is doable using cmake. I can help out if needed.

done

**Pull request merged**
